### ISSUE TITLE
Can access other user's show info through the url despite not having the permissions to view their pages

### ISSUE THREAD

**Issue by Luke2v52** [git-flash/FLASH#94]

**Comment by Buzzec** [comment]
Can you give an example url?

**Comment by Luke2v52** [comment]
Absolutely good sir! Here you go! http://localhost:3000/attendance_user/9

**Comment by Buzzec** [comment]
localhost...

**Comment by Luke2v52** [comment]
https://flashpoint8.herokuapp.com/attendance_user/9 I changed the link to end with 9 since during testing we could not get values to work other than 9

**Comment by sumedhtadimeti** [comment]
Complete
